package utils

var (
	CapybaraFacts = []string{
		"Capybaras are the largest rodents in the world.",
		"They are semi-aquatic animals and are excellent swimmers.",
		"Native to South America, capybaras can be found in countries such as Brazil, Venezuela, Colombia, and Paraguay.",
		"Capybaras are social animals and live in groups of up to 20 individuals, although larger groups have been observed.",
		"Groups of capybaras are led by a dominant male, who protects the group and helps to raise the young.",
		"Capybaras have webbed feet, which makes them excellent swimmers.",
		"They are also able to hold their breath for up to five minutes.",
		"Capybaras are herbivores and feed mainly on grasses and aquatic plants.",
		"They have a unique digestive system that allows them to extract nutrients from tough plants.",
		"Capybaras have a lifespan of around 8-10 years in the wild and up to 12 years in captivity.",
		"Female capybaras give birth to litters of around 4-5 young, known as pups.",
		"Pups are born fully furred and with their eyes open, and are able to walk within a few hours.",
		"Capybaras have a thick, coarse coat that helps to protect them from the cold.",
		"Their fur is highly prized and is used in the production of luxury goods.",
		"Capybaras are preyed upon by a variety of predators, including jaguars, anacondas, and caimans.",
		"They use their keen senses of smell and hearing to detect potential danger.",
		"Capybaras are highly adaptable animals and can thrive in a variety of habitats, including wetlands, grasslands, and forests.",
		"They are known to be excellent swimmers and have been observed diving up to 5 meters (16 feet) deep.",
		"Capybaras are sometimes kept as pets, although this is illegal in many countries.",
		"They are also used for their meat and their hides, which are used to make leather.",
		"Capybaras are very social animals and are known to engage in a variety of behaviors, including grooming, playing, and vocalizing.",
		"They have a variety of vocalizations, including barks, whistles, and purrs.",
		"Capybaras are known to form close bonds with other members of their group and will often groom each other.",
		"They are also known to engage in alloparenting, where females will take care of each other's young.",
		"Capybaras are sometimes called 'water pigs' because of their love of water.",
		"They have been observed soaking in hot springs to regulate their body temperature.",
		"Capybaras have a unique digestive system that allows them to extract nutrients from tough plants.",
		"They are able to ferment cellulose in their hindgut, which allows them to break down tough plant material.",
		"Capybaras are able to conserve water by producing dry feces and reabsorbing water from their bladder.",
		"They are also able to survive without access to fresh water for long periods of time.",
		"Capybaras are known to be intelligent animals and are able to learn from experience.",
		"They have been observed using tools, such as sticks, to aid in feeding.",
		"Capybaras are often hunted for their meat and hides, which are used for food and leather.",
	}
)
