package utils

var (
	CapybaraFacts = []string{
		// Data courtesy of https://animalfacts.blog/fun-facts-about-capybaras/
		"Capybaras are semi-aquatic animals, spending a lot of their time in water.",
		"They are excellent swimmers and can stay underwater for up to five minutes at a time.",
		"Capybaras are native to South America and can be found in Panama, Venezuela, Colombia, Argentina, and Brazil.",
		"They can weigh up to 140 pounds, making them the world's largest rodents.",
		"Despite their hefty size, capybaras are quick and can reach speeds up to 22 mph.",
		"They have webbed feet which help them paddle in the water.",
		"The name 'capybara' comes from the Tupi language and means 'one who eats slender leaves.'",
		"Capybaras have a lifespan of 8-10 years in the wild, but can live up to 12 years in captivity.",
		"Their teeth never stop growing, just like other rodents.",
		"Capybaras are social animals and live in groups ranging from 10 to 20 individuals.",
		"In the wild, they have been known to form herds of up to 100 individuals.",
		"Capybaras communicate through a combination of scent marking and vocal sounds, including purrs, barks, whistles, and grunts.",
		"Their eyes, ears, and nostrils are all positioned high on their head so they can remain alert to predators even when they're in the water.",
		"Capybaras eat their own feces to aid digestion and get the maximum amount of nutrients from their food.",
		"The capybara's jaw hinge is not perpendicular, so they chew food by grinding back-and-forth rather than side-to-side.",
		"They are a favorite meal of jaguars, pumas, ocelots, harpy eagles, and caimans.",
		"To avoid predators, capybaras are most active during dawn and dusk, which makes them crepuscular.",
		"Capybaras are highly vocal animals and will make a variety of noises to communicate with their group, including barks, whistles, and grunts.",
		"They have a gestation period of about 130-150 days and usually give birth to 4-5 babies at a time.",
		"Capybaras are great climbers and will often climb onto tree stumps and logs to look out for danger.",
		"Their scientific name, Hydrochoerus hydrochaeris, is Greek for 'water hog.'",
		"Despite their large size, capybaras are very agile and can easily maneuver through the thick underbrush of their native habitats.",
		"Capybaras have even been known to play with other animals, including kittens and puppies.",
		"Capybara skin secretes a substance that is thought to be a natural sunscreen.",
		"Their skin dries out easily, so they need to live near water bodies to hydrate it regularly.",
		"They have a special digestive system that allows them to ferment food, break down cellulose and absorb nutrients.",
		"Capybaras love to roll in the mud to keep cool and protect their skin from the sun.",
		"Although they are relatively tame, they can bite when they feel threatened.",
		"Capybaras are very flexible and can sleep in any position, including on their backs with their feet in the air.",
		"The largest recorded capybara weighed 232 pounds!",
		"They have been known to allow small birds to perch on their backs.",
		"Capybaras can eat up to eight pounds of grass a day.",
		"Their preferred habitats are densely forested areas near bodies of water.",
		"Capybaras are excellent divers and can even sleep underwater, keeping their noses just above the water line.",
		"Their incisors can grow up to five inches long.",
		"Capybaras are not an endangered species, but they are hunted for their meat and hide.",
		"Unlike many rodents, capybaras do not have a tail.",
		"In Japan, capybaras are allowed to roam freely in hot springs in winter.",
		"Capybaras are known to form symbiotic relationships with other animals. For example, birds eat insects off their backs.",
		"They have a slow reproductive rate, with females usually only producing one litter every year.",
		"Capybaras have been introduced into Florida, USA, and have established a small breeding population there.",
		"Their large size allows them to eat tall grasses and reeds that smaller rodents can't reach.",
		"They are herbivores, their diet consists mainly of grasses and aquatic plants.",
		"Capybaras have a calm and gentle demeanor, which makes them popular in zoos and sometimes as pets.",
		"When capybaras are happy, they make a noise that sounds like purring.",
		"Despite their size, they are good at hiding and can camouflage themselves in tall grass.",
		"Capybaras are sometimes kept as pets, but they require a lot of space and access to water.",
		"Their social structure is similar to that of some primates, with a dominant male, females, juveniles, and subordinate males.",
		"Capybara babies, called pups, are able to walk and swim shortly after birth.",
		"The capybara's closest relatives are guinea pigs and rock cavies.",
		"Capybaras often serve as a 'mobile home' for semi-parasitic cowbirds that eat the insects off their backs.",
		"Unlike other rodents, capybaras do not hoard their food.",
		"Capybaras in the wild have been observed 'babysitting' the young of other capybaras.",
		"Capybaras can make around 50 different sounds to communicate with each other.",
		"The capybara's feet are slightly webbed which makes them excellent swimmers.",
		"They have a slow metabolic rate, which is why they can survive on a diet of low-nutrient grasses.",
		"Capybaras love wallowing in mud, as it helps to regulate their body temperature.",
		"They're not great jumpers, but they can jump over obstacles that are about 3-4 feet high.",
		"If capybaras get too hot, they can sweat through their noses.",
		"During the rainy season, capybaras can sleep underwater with only their noses sticking out.",
		"Capybaras are popular in Japan, where they are often seen in hot springs and zoos.",
		"Some birds use capybaras as perches or platforms from which to hunt or scout.",
		"Capybaras have a barrel-shaped body which helps them to stay buoyant in the water.",
		"Despite being semi-aquatic, capybaras have fur rather than waterproof hair.",
		"A capybara's fur can range from a light brown to a dark, almost black color.",
		"Their sweat has a sweet, grassy odor.",
		"They have a highly developed sense of smell, which they use to find food and detect predators.",
		"The capybara's digestive system is similar to that of a cow, and they have a large cecum for fermenting plant material.",
		"Capybaras are crepuscular animals, meaning they are most active during dawn and dusk.",
		"The Catholic Church once classified capybaras as fish so they could be eaten during Lent.",
		"Capybaras have poor vision, but their senses of smell and hearing are excellent.",
		"When threatened, capybaras can emit a bark-like sound to warn others in their group.",
		"Capybaras have two types of fur: a coarse outer layer and a soft undercoat.",
		"Their jaws are powerful and can easily tear through tough grass and aquatic plants.",
		"When swimming, capybaras use their long, stiff whiskers to navigate.",
		"Capybaras are very vocal animals and have a range of different calls, including barks, whistles, and purrs.",
		"Some capybaras have been observed 'adopting' orphaned pups and raising them as their own.",
		"They have a specialized stomach that helps them digest cellulose in grasses.",
		"When sleeping, capybaras often lean against each other for support.",
		"Capybaras can sleep with their eyes open.",
		"Their nostrils, eyes, and ears are located high on their heads so they can remain submerged in the water while still being able to see, hear, and breathe.",
		"They use their large, sharp incisors to dig for roots and bulbs.",
		"Capybaras in the wild have been observed using their teeth to defend themselves against predators.",
		"They can swim as fast as they can run.",
		"The shape of a capybara's footprint is often described as a 'star.'",
		"Female capybaras are often larger than males.",
		"Capybaras can recognize the sound of their own names.",
		"They enjoy lounging in the sun and will often stretch out to sunbathe.",
		"Capybaras are known to be very patient and will often allow small animals to climb on them.",
		"They have a unique digestive adaptation called coprophagy where they consume their feces to extract maximum nutritional value from food.",
		"Capybaras have a unique vocalization that sounds like a series of clicks, which is thought to be used in courtship.",
		"Their ears are lined with soft, white fur.",
		"The large size of capybaras allows them to eat taller grasses and reeds that smaller rodents can't reach.",
		"The average capybara consumes 6 to 8 pounds of grass per day.",
		"They have a specialized stomach that helps them digest tough cellulose in grass.",
		"Capybaras are very affectionate and will often nuzzle and lick each other.",
		"They are great at jumping and can clear obstacles up to 4 feet high.",
		"Capybaras have a large, barrel-shaped body, which helps them to float in water.",
		"They are known to be tolerant of a variety of animals and have been observed cohabiting with a range of species in zoos.",
		"Capybaras are incredibly adaptive and have been found in a variety of habitats, from dry grasslands to lush rainforests.",
	}
)
